# -*- coding: utf-8 -*-
"""KingdomGame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdJnwd2XTas9xiY_GQzwQPydof021d7_
"""

import math
from termcolor import colored

def print_banner():
    print(colored("===============================================", 'cyan'))
    print(colored("╔═══════════════════════════════════════════╗", 'magenta'))
    print(colored("║              WELCOME TO THE               ║", 'yellow', attrs=['bold']))
    print(colored("║               KINGDOM GAME                ║", 'yellow', attrs=['bold']))
    print(colored("╚═══════════════════════════════════════════╝", 'magenta'))
    print(colored("===============================================\n", 'cyan'))

def actions():
    global action

    print("\nChoose your action:")
    print(colored("➤ A. Host a banquet", 'yellow'))
    print(colored("➤ B. Create jobs", 'green'))
    print(colored("➤ C. Hold festival", 'blue'))
    print(colored("➤ D. Collect emergency taxes", 'red'))
    print(colored("➤ E. End current day", 'magenta'))

    action = input(colored("\nWhat would you like to do? ", 'cyan')).upper()
    return action

def check_result():
    global game_result, money, happiness, population

    if money <= 0 or happiness <= 0:
        game_result = "LOSE"
    elif population >= 2000:
        game_result = "WIN"
    elif money >= 6000 and population >= 1000:
        game_result = "WIN"

money = 100.00
population = 20
happiness = 20
current_day = 1
game_result = ""

print_banner()
print(colored("Welcome to your kingdom! We serve at your command.\n", 'cyan'))
while game_result not in ['WIN', 'LOSE']:
    action = ""
    while action != 'E':
        print(colored(f"\nCurrent Kingdom Statistics (Day {current_day}):", 'cyan'))
        print(colored(f"╔════════════════════════╗", 'yellow'))
        print(colored(f"║ Population: {population:>10} ║", 'yellow', attrs=['bold']))
        print(colored(f"║ Happiness: {happiness:>10}  ║", 'green', attrs=['bold']))
        print(colored(f"║ Money:    {money:>10.2f}   ║", 'blue', attrs=['bold']))
        print(colored(f"╚════════════════════════╝\n", 'yellow'))

        action = actions()

        if action in "ABCDE":
            if action == "A":
                if money < 200:
                    print(colored("\nYou do not have enough money to host a banquet.\n", 'red'))
                else:
                    money -= 200
                    happiness += 20
                    print(colored("\nYou hosted a splendid banquet! 🎉\n", 'yellow'))
            elif action == "B":
                if money < 50:
                    print(colored("\nYou do not have enough money to create jobs.\n", 'red'))
                else:
                    money -= 50
                    population += 5
                    print(colored("\nYou created new jobs and boosted the economy! 💼\n", 'green'))
            elif action == "C":
                if money < 500:
                    print(colored("\nYou do not have enough money to hold a festival.\n", 'red'))
                else:
                    money -= 500
                    happiness += 15
                    population += 40
                    print(colored("\nYou held a grand festival! The people rejoice! 🎪\n", 'blue'))
            elif action == "D":
                money += population * 5
                happiness -= math.floor(population * 0.20)
                print(colored("\nYou collected emergency taxes to fill the treasury. 💰\n", 'red'))
            elif action == "E":
                print(colored("\nYou ended the day. 🌙\n", 'magenta'))
        else:
            print(colored("\nInvalid input. Please select a valid action.\n", 'red'))

    if current_day % 5 == 0:
        population += ((math.floor(current_day / 5)) ** 2)

    if current_day % 9 == 0:
        happiness -= math.floor(population * 0.05)

    if current_day % 3 == 0:
        money += population * 1.5

    if current_day % 6 == 0 and current_day % 12 != 0:
        money += 10
        happiness += 2

    if current_day != 11 and current_day % 11 == 0:
        money -= 100
        happiness -= 5

    if current_day % 31 == 0:
        money += 6
        happiness += 6
        population += 6

    count = str(current_day).count("7")
    if "7" in str(current_day):
        money -= (7 * count)
        population -= (7 * count)
        happiness -= (7 * count)

    if current_day % 50 == 0:
        money -= math.floor(money / 2)
        population -= math.ceil(population / 4)

    check_result()

    if game_result in ["WIN", "LOSE"]:
        print(colored("===============================================", 'cyan'))
        if game_result == "WIN":
            print(colored("╔═══════════════════════════════════════════╗", 'green'))
            print(colored("║ Congratulations! You've transformed your  ║", 'green', attrs=['bold']))
            print(colored("║ kingdom into a world wonder! You win! 🎉  ║", 'green', attrs=['bold']))
            print(colored("╚═══════════════════════════════════════════╝", 'green'))
        else:
            print(colored("╔═══════════════════════════════════════════╗", 'red'))
            print(colored("║ Alas, your kingdom has fallen into ruin.  ║", 'red', attrs=['bold']))
            print(colored("║ You lose the game. 💔                      ║", 'red', attrs=['bold']))
            print(colored("╚═══════════════════════════════════════════╝", 'red'))

        print(colored(f"Game finished on day: {current_day}\n", 'cyan'))
        print(colored("Final Kingdom Statistics:", 'cyan'))
        print(colored(f"Population: {population}", 'yellow', attrs=['bold']))
        print(colored(f"Happiness: {happiness}", 'green', attrs=['bold']))
        print(colored(f"Money: {money:.2f}\n", 'blue', attrs=['bold']))
    else:
        current_day += 1