# -*- coding: utf-8 -*-
"""Code_SimpleKingdomGame

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1IW0XMVLvykRWNMqQUrzs-pNrjULumU
"""

import math

def actions():

    global action

    print("Actions:")
    print("A. Host a banquet")
    print("B. Create jobs")
    print("C. Hold festival")
    print("D. Collect emergency taxes")
    print("E. End current day")

    action = input("\nWhat would you like to do? ")
    return action

def checkResult():

    global game_result
    global money, happiness, population

    if money <=0 or happiness <=0:
        game_result = "LOSE"
    elif population >= 2000:
        game_result = "WIN"
    elif money >= 6000 and population >= 1000:
        game_result = "WIN"

money = 100.00
population = 20
happiness = 20
current_day = 1
game_result = str()

print("Welcome to your kingdom! We serve at your command.\n")
while(game_result not in ['WIN','LOSE']):

    action = str()
    while(action != 'E'):
        print("Current kingdom statistics (Day {}):".format(current_day))
        print("Population: {}".format(population))
        print("Happiness: {}".format(happiness))
        print("Money: {}\n".format(format(money, '.2f')))
        action = actions()

        if action in "ABCDE":
            if action == "A":
                if money < 0:
                    print("\nYou do not have enough money to do that.\n")
                else:
                    money -= 200
                    happiness += 20
                    print("\nYou selected to host a banquet.\n")
            elif action == "B":
                if money < 0:
                    print("\nYou do not have enough money to do that.\n")
                else:
                    money -= 50
                    population += 5
                    print("\nYou selected to create jobs.\n")
            elif action == "C":
                if money < 0:
                    print("\nYou do not have enough money to do that.\n")
                else:
                    print("\nYou selected to hold a festival.\n")
                    money -= 500
                    happiness += 15
                    population += 40
            elif action == "D":
                money += (population*5)
                happiness -= math.floor(population*.20)
                print("\nYou selected to collect the emergency taxes.\n")
            elif action == "E":
                print("\nYou selected to end the day.\n")

        else:
            print("\nInvalid input. Please input based on the input above.\n")


    if current_day % 5 == 0:
        population += ((math.floor(current_day/5))**2)

    if current_day % 9 == 0:
        happiness -= math.floor(population*.05)

    if current_day % 3 == 0:
        money += population*(1.5)

    if current_day % 6 == 0 and current_day % 12 != 0:
        money += 10
        happiness += 2

    if current_day != 11 and current_day % 11 == 0:
        money -= 100
        happiness -= 5

    if current_day % 31 == 0:
        money += 6
        happiness += 6
        population += 6


    count = str(current_day).count("7")
    if "7" in str(current_day):
        money -= (7*count)
        population -= (7*count)
        happiness -= (7*count)

    if current_day % 50 == 0:
        money -= math.floor(money/2)
        population -= math.ceil(population/4)

    checkResult()

    if game_result == "WIN" or game_result == "LOSE":
        if game_result == "WIN":
            print("==========")
            print("You've transformed your kingdom into a world wonder! Great job! You win the game.\n")

        else:
            print("==========")
            print("Sorry, your kingdom has been run into the ground. You lose.\n")

        print("Finished the game on day: {}\n".format(current_day))
        print("Final kingdom statistics:")
        print("Population: {}".format(population))
        print("Happiness: {}".format(happiness))
        print(f"Money: {format(money, '.2f')}\n")

    else:
        current_day += 1